CREATE TABLE DEPARTMENT(
ID INT PRIMARY KEY NOT NULL,
DEPARTMENTNAME NVARCHAR(100) NOT NULL,
LOCATION NVARCHAR(50) NOT NULL,
DEPARTMENTHEAD NVARCHAR(100) NOT NULL);
SELECT * FROM DEPARTMENT;
INSERT INTO DEPARTMENT VALUES(1,'IT','PUNE','ROHIT');
INSERT INTO DEPARTMENT VALUES(2,'PAYROLL','DELHI','JAY');
INSERT INTO DEPARTMENT VALUES(3,'HR','HYDRABAD','AJAY');
INSERT INTO DEPARTMENT VALUES(4,'OTHER DEPARTMENT','MUMBAI','VAIBHAV');